### ISSUE TITLE
MySql docker container

### ISSUE THREAD

**Issue by robert-gauto** [cthulhu666/docker-livehelperchat#2]
How to link a mysql docker container?

**Comment by cthulhu666** [comment]
Please take a look at updated README: you can use Docker Compose to set up both application and database for you - they will have their own subnet and database will be visible under the hostname `db`.

If you want to link your own mysql container, then you can use docker links, as described here: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/
